### ISSUE TITLE
Does not work under Node.js v6 on macOS

### ISSUE THREAD

**Issue by sonicdoe** [SonicHedgehog/detect-character-encoding#10]
`node-gyp rebuild` produces quite a few `error: no type named 'nullptr_t' in namespace 'std'` errors.

Originally reported in #9.

**Comment by alanjames1987** [comment]
I'm having the same problem on OS X 10.12.6 running Node 6.9.4, NPM 3.10.10. I can provide any other information needed to reproduce this.

**Comment by alanjames1987** [comment]
Additionally I don't get this error in *buntu 16.04 with the same version of Node and NPM installed.

I'm also using LLVM version 8.1.0.

**Comment by sonicdoe** [comment]
This should now be fixed in detect-character-encoding v0.5.1.
