### ISSUE TITLE
Failed to install on debian.

### ISSUE THREAD

**Issue by RomanBurunkov** [SonicHedgehog/detect-character-encoding#14]
Got the following errors:

`
node_modules/detect-character-encoding/build/Release/icuWrapper.node: undefined symbol: ucnv_open_61

`

or

`
node_modules/detect-character-encoding/build/Release/icuWrapper.node: undefined symbol: ucnv_open_59

`

**Comment by sonicdoe** [comment]
Which versions of detect-character-encoding, Node.js, and Debian are you using? I couldn’t reproduce this issue with Node.js v10 under Debian 9.5.

**Comment by RomanBurunkov** [comment]
Hello @sonicdoe ,

It was Debian Jessie and Node 8.12.
I've tried latest version of 'detect-character-encoding'.

**Comment by RomanBurunkov** [comment]
Error with 'ucnv_open_59' I got when installed 'detect-character-encoding' with npm.

And 'ucnv_open_61' when built package from sources.

**Comment by sonicdoe** [comment]
Are you using a 32-bit installation by any chance? I’m getting the same error on a 32-bit Debian 8.10 machine (but not on a 64-bit one).

**Comment by RomanBurunkov** [comment]
Hello @sonicdoe ,

I've checked my installation and can confirm that it is a 32-bit Debian 8.

**Comment by sonicdoe** [comment]
Thanks for checking, detect-character-encoding actually does not support 32-bit operating systems. I mentioned this in the readme before but inadvertently removed it in [`03e1c58`](https://github.com/sonicdoe/detect-character-encoding/commit/03e1c589faa40fe67e105b0393812b31dcff98b9#diff-04c6e90faac2675aa89e2176d2eec7d8L42). I’ve added the notice back now in https://github.com/sonicdoe/detect-character-encoding/commit/f23147a594892eb4580b3ea62aa10c64a7313a56.

If you are not tied to ICU, I’d suggest taking a look at [ced](https://github.com/sonicdoe/ced) which does work on Debian 8 x86.
