### ISSUE TITLE
A native crash

### ISSUE THREAD

**Issue by letme2010** [SonicHedgehog/detect-character-encoding#15]
########CRASH STACK:
#0  0x00007fbf4050ea21 in icu_59::CharsetMatch::getName() const ()
   from /home/tuna/papilio/node_modules/detect-character-encoding/build/Release/icuWrapper.node
#1  0x00007fbf4050d35b in DetectCharacterEncoding(Nan::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/tuna/papilio/node_modules/detect-character-encoding/build/Release/icuWrapper.node
#2  0x00007fbf4050cf96 in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/tuna/papilio/node_modules/detect-character-encoding/build/Release/icuWrapper.node

########USE THIS DEMO TO REAPPEARS:
function main() {
	console.log("=====START=====");
	let rawData = new Buffer('AD', 'hex');
	const detectCharacterEncoding = require('detect-character-encoding');
	const charsetMatch = detectCharacterEncoding(rawData);
	console.log("=====END=====", charsetMatch.encoding);
}

########FIXUP DIFF:
diff --git a/icuWrapper.cpp b/icuWrapper.cpp
index a228fe0..8d0bba3 100644
--- a/icuWrapper.cpp
+++ b/icuWrapper.cpp
@@ -34,6 +34,12 @@ NAN_METHOD(DetectCharacterEncoding) {
 
        charsetMatch = ucsdet_detect(charsetDetector, &errorCode);
 
+       if(NULL == charsetMatch) {
+               Nan::ThrowError("Failed to charset not match.");
+                ucsdet_close(charsetDetector);
+                return;
+       }
+
        if(U_FAILURE(errorCode)) {
                Nan::ThrowError("Failed to detect charset.");
                ucsdet_close(charsetDetector);

**Comment by sonicdoe** [comment]
Thank you! I’ve released a fix in v0.7.0 🎉
