### ISSUE TITLE
I can't install detect-character-encoding.

### ISSUE THREAD

**Issue by crocket** [SonicHedgehog/detect-character-encoding#2]
nodejs version : v5.3.0
npm version : 3.5.2
Operating System : ArchLinux 64bit

```
% npm install --save detect-character-encoding

> detect-character-encoding@0.2.0 install /home/elisa/repos/mine/convert-to-utf8/node_modules/detect-character-encoding
> node-gyp rebuild

gyp: name 'icu_ver_major' is not defined while evaluating condition 'icu_ver_major == 54' in vendor/icu/icu.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
```

**Comment by sonicdoe** [comment]
Could you retry with v0.2.1? v0.2.0 was missing [config.gypi](https://github.com/SonicHedgehog/detect-character-encoding/blob/v0.2.0/config.gypi) in the npm package which caused `icu_ver_major` to be undefined.

**Comment by crocket** [comment]
Now, v0.2.1 can be installed on my system.
