### ISSUE TITLE
Unable to install on ubuntu 18.04

### ISSUE THREAD

**Issue by hassanrafay** [SonicHedgehog/detect-character-encoding#20]
please see the error log and guide me, I have tried everything but it is not working

/home/rafay/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20191030-19:28:01.750(5)? (STDERR) 						throw(ex);
W20191030-19:28:01.750(5)? (STDERR) 						^
W20191030-19:28:01.750(5)? (STDERR) 
W20191030-19:28:01.750(5)? (STDERR) Error: The module '/home/rafay/Documents/work/denis/node_modules/detect-character-encoding/build/Release/icuWrapper.node'
W20191030-19:28:01.751(5)? (STDERR) was compiled against a different Node.js version using
W20191030-19:28:01.751(5)? (STDERR) NODE_MODULE_VERSION 64. This version of Node.js requires
W20191030-19:28:01.751(5)? (STDERR) NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
W20191030-19:28:01.751(5)? (STDERR) the module (for instance, using `npm rebuild` or `npm install`).
W20191030-19:28:01.751(5)? (STDERR)     at Object.Module._extensions..node (module.js:682:18)
W20191030-19:28:01.751(5)? (STDERR)     at Module.load (module.js:566:32)
W20191030-19:28:01.752(5)? (STDERR)     at tryModuleLoad (module.js:506:12)
W20191030-19:28:01.752(5)? (STDERR)     at Function.Module._load (module.js:498:3)
W20191030-19:28:01.752(5)? (STDERR)     at Module.require (module.js:597:17)
W20191030-19:28:01.752(5)? (STDERR)     at require (internal/module.js:11:18)
W20191030-19:28:01.757(5)? (STDERR)     at bindings (/home/rafay/Documents/work/denis/node_modules/bindings/bindings.js:112:48)
W20191030-19:28:01.757(5)? (STDERR)     at Object.<anonymous> (/home/rafay/Documents/work/denis/node_modules/detect-character-encoding/index.js:3:37)
W20191030-19:28:01.758(5)? (STDERR)     at Module._compile (module.js:653:30)
W20191030-19:28:01.758(5)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
W20191030-19:28:01.758(5)? (STDERR)     at Module.load (module.js:566:32)
W20191030-19:28:01.758(5)? (STDERR)     at tryModuleLoad (module.js:506:12)
W20191030-19:28:01.758(5)? (STDERR)     at Function.Module._load (module.js:498:3)
W20191030-19:28:01.759(5)? (STDERR)     at Module.require (module.js:597:17)
W20191030-19:28:01.759(5)? (STDERR)     at require (internal/module.js:11:18)
W20191030-19:28:01.759(5)? (STDERR)     at npmRequire (/home/rafay/Documents/work/denis/.meteor/local/build/programs/server/npm-require.js:133:10)
W20191030-19:28:01.759(5)? (STDERR)     at Module.useNode (packages/modules-runtime.js:664:18)
W20191030-19:28:01.760(5)? (STDERR)     at index.js (packages/modules.js:790:8)
W20191030-19:28:01.760(5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20191030-19:28:01.760(5)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20191030-19:28:01.760(5)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20191030-19:28:01.761(5)? (STDERR)     at utils.js (imports/api/server/utils.js:5:33)

**Comment by sonicdoe** [comment]
Your error log contains the following message:

> Error: The module '/…/detect-character-encoding/build/Release/icuWrapper.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 64. This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing the module (for instance, using npm rebuild or npm install).

Did you already try this suggestion?

**Comment by hassanrafay** [comment]
@sonicdoe Yes, I tried it and I was able to fix the error by downgrading node version.
