### ISSUE TITLE
Module version mismatch. Expected 50, got 48

### ISSUE THREAD

**Issue by cawa-93** [SonicHedgehog/detect-character-encoding#5]
I try use `detect-character-encoding` in Desktop app with Electron.
But i have this error:
```
Uncaught Error: Module version mismatch. Expected 50, got 48.
```
In
```
/app/node_modules/bindings/bindings.js:83
```

**Comment by sonicdoe** [comment]
This error is caused by having detect-character-encoding compiled against a different Node.js version than the one you are currently using. Could you take a look at https://github.com/electron-userland/electron-builder/issues/453 and see if it resolves your issue?
