### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by myhere** [SonicHedgehog/detect-character-encoding#9]
hi:
   i install failed, message as below, thanks.

### env: 
- macOS: 10.12.1 (16B2657)
- nodejs: v8.1.4

### error screenshot:

![image](https://user-images.githubusercontent.com/515630/29345669-d2457c4c-8272-11e7-977b-4dbbb7064e32.png)

**Comment by sonicdoe** [comment]
I’m not able to reproduce this under macOS v10.12.6 and Node.js v8.1.4. Which version of detect-character-encoding are you trying to install?

**Comment by myhere** [comment]
hi, @sonicdoe 

sorry, i supplied a wrong node.js version above.
my `package.json` specified `engines` field: [alinode@2.2.0](https://alinode.aliyun.com/doc/alinode_versions),which depends on node@6.11.0. 
i upgraded alinode version and it install successfully.

install is ok in an empty dir with the above env(macOS: 10.12.1/nodejs: v8.1.4).

thanks!
